WHITESPACE = _{" " | "\t" | "\n" | "\r"}

json = _{ value }
value = _{ object | array | string | number | literal }

object = _{ "{" ~ members ~ "}" }
member = _{ string ~ ":" ~ value }
members = _{ (member ~ ("," ~ member)*)? }

array = _{ "[" ~ items ~ "]" }
items = _{ (value ~ ("," ~ value)*)? }

string = _{ "\"" ~ char* ~ "\"" }
char = _{
	!("\"" | "\\") ~ ANY
	| "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
	| "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

int = _{ "0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT* }
frac = { "." ~ ASCII_DIGIT+ }
exp = { ^"e" ~ ("-" | "+")? ~ ASCII_DIGIT+ }
number = _{ ("-"? ~ int ~ frac? ~ exp?) }

literal = _{ "true" | "false" | "null" }
